import "../globals.css";

export const metadata = {
  title: "Portfolio -- You want a website, I can help you with that!!!",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
