import "../globals.css";

export const metadata = {
  title: "Portfolio -- you want a website,I can help that!",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
