import Footer from "../(site)/footer/page";
import Navbar from "../(site)/navbar/page";
import "../globals.css";

export const metadata = {
  title: "Portfolio -- You want a website, I can help you with that!!!",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
       
        <Navbar />
        {children}
        <Footer />
       
      </body>
    </html>
  );
}
